import '../globals.css';
import { Roboto } from 'next/font/google';

import Providers from '@/components/Providers';
import Navbar from '@/components/Navbar';
import { Providers as RTKProvider } from '@/libs/store/Provider';

const font = Roboto({ weight: ['100', '300', '400', '500', '700'], subsets: ['latin'] });

export const metadata = {
  title: 'Spotify App',
  description: 'Generated by Phol',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <Providers>
          <RTKProvider>
            <Navbar />
            {children}
          </RTKProvider>
        </Providers>
      </body>
    </html>
  );
}
